// Define your messages
const messages = {
    allreadyHaveAccount: "Already have account, Please Login",
    emailAlreadyExists: 'The email address is already in use.',
    userRegistered: 'User registration successful.',
    internalServerError: 'An internal server error occurred.',
    accountNotFound: "Account not found. Please check your details.",
    invalidPassword: "Invalid password.",
    loginSuccess: 'Login successfully.',
    emailNotFound: 'Email address not found. Please enter a valid email.',
    passwordResetLinkSentSuccesfully: 'Password reset link sent to your email.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    dataNotFound: "Data not found",
    passwordChanged: "Password changed successfully",
    passwordNotChanged: "Password not changed",
    passwordsDoNotMatch: 'Passwords do not match.',
    dataFoundSuccessful: 'Data found successfully',
    freeDemoRegistered: 'Free demo registration successful.',
    freeDemoNotFound: "No users found for the free demo.",
    idRequire: "Id must be require",
    dataAddedSuccessfull: "Data Added Sucessfully",
    freeDemoNotFoundOnGivenId: "No user found for the given ID in the free demo.",
    scheduleAdded: 'Schedule added successfully.',
    serverRunning: 'Node app is running on the specified port',
    passwordResetLink: "Please click the link below to reset your password.",
    passwordResetSubject: "Password Reset Request",
    invalidLink: "Invalid link. Please request a new one.",
    pageNotFound: "404 Error, Page Not Found",
    errorToSendingEmail: "Error sending email",
    dbConnectionError: 'Error when connecting to db:',
    dbConnectionSuccess: 'Connected to MySQL Server!',
    dbConnectionClosing: 'Closing database connection',
    dbError: 'Database connection error:',
    protocolConnectionLost: 'Database connection was lost. Reconnecting...',
    NO_TOKEN_PROVIDED: 'Unauthorized: No token provided',
    INVALID_OR_MISSING_TOKEN: 'Unauthorized: Invalid or missing token',
    INVALID_TOKEN: 'Unauthorized: Invalid token',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    BILLING_INFO_ADD: "Your billing information has been saved successfully.",
    verifiedMessage: "Please click below link to email verified.",
    forgotPassword: "Forgot Password",
    accountActivate: "Activate account",
    accountVerifiedLinkSent: "Account verified link sent successfully. Please check your email ",
    failedToUsersCreate: "Failed to create user. Please try again later",
    accountVerifiedCodeSent: "Your account verification code has been sent to your registered email address. Please check your inbox to proceed with the verification.",
    otpVerified: "Your OTP has been successfully verified.",
    invalidOtp: "Invalid OTP. Please try again.",
    forgotPasswordOtpSend: "Your OTP for resetting your password has been sent to your registered email. Please check your inbox to proceed.",
    passwordAndConfirmPasswordNotMatch: "Password and Confirm Password do not match",
    userDetailedFoundSuccessfully: "User details retrieved successfully.",
    profileUpdatedSuccessfully: "Profile updated successfully!",
    userBlockedSuccessfully: "User has been successfully blocked.",
    userUnBlockedSuccessfully: "The user has been unblocked successfully.",
    hasFollowingYou: "started following you!",
    hasFollowCheckProfile: "has followed you. Check their profile now!",
    notificationSentSuccessfull: 'The notification was successfully sent!',
    notificationSendFailed: "Notification delivery failed for one or more recipients",
    unableToSendNotification: "Unable to send the notification. Please try again later.",
    requestSentSucessfull: "Request sent successfully.",
    requestNotSent: "The request could not be sent. Please try again.",
    requestAcceptSuccessfully: "Request Accepted Successfully",
    requestDecalinedSuccessfully: "Request Declined Successfully",
    unFollowedToUsers: "You have unfollowed this user.",
    postFoundSuccessfull: "The post has been found successfully.",
    postNotFound: "No post found.",
    likePost: "You have liked this post successfully.",
    unLikePost: "You have unliked this post.",
    commentAdded: "Your comment has been added successfully.",
    commentDelete: "Your comment has been deleted successfully.",
    insertError: "Failed to insert data into the database. Please try again later.",
    followSuccess: "You have successfully followed the user.",
    postCreate: "Post created successfully.",
    postCreatedFailed: "Post creation failed. Please try again.",
    notificationFetchSuccessfully: "Notifications retrieved successfully.",
    notificationFailedToFetch: "No notifications found for this user.",
    accountDeleteSuccessfull: "Your account has been successfully deleted.",
    accountNotDelete: "There was an error, and your account was not deleted",
    commentsPostedSuccessfull: "Comment posted successfully.",
    likeOnComments: "You liked this comment.",
    removeLikeCommentsOnPost: "Comment unlike successful.",
    notification: "Notification ",
    giveawayAnnoucment: "Give Away Annoucment ",
    wrongToggleType: "Plz Provide Proper Toggle Type",
    deleteCommentsSuccessfully: "Comment removed successfully.",
    failedToCommentsDelete: "Failed to delete the comment. Please try again.",
    hasCommentedCheckPost: "left a comment on your post. Check it out now!",
    commentOnPosts: "commented on your post",
    likeOnPost: "liked your post",
    hasLikedCheckPost: "just liked your post. See what’s trending!",
    userNotFound: "User not found",
    notificationDeleted: "Notification deleted successfully.",
    notificationsDeleteFailed: "Notification could not be deleted.",
    noFilesUploaded: "No files uploaded",
    postDeleted: "Post deleted successfully.",
    postNotDeleted: "Post not deleted.",
    postUpdateSucessfully: "Post updated successfully!",
    postFailedToUpdate: "Failed to update the post. Please try again later.",
    userSupport: "New Contact Support Request",
    supportRequestSent: "Support request sent successfully!",
    failedToSentRequest: "Failed to send request. Please try again later.",
    supportCategoryFoundSuccess: "Support Categories Found Successfully",
    supportCategoryNotFound: "Support Categories Not Found",

    // -----------------------seller message ---------------------------------//

    categoryFoundSuccessful: 'Category found successfully',
    categoryNotFound: 'Category not found successfully',
    sellerFormSubmission: "Your seller application has been submitted successfully. It is now pending approval from the admin.",
    sellerInfoUpdateSuccessfully: "Seller information updated successfully.",
    sellerInfoNotUpdate: "Seller information could not be updated.",
    hasApprovedAsSeller: "has been approved as a seller! 🎉",
    hasApprovedBodyData: "Your seller account has been successfully approved. You can now start selling on our platform.",
    hasRejectAsASeller: "Seller Application Rejected",
    hasRejectBodyData: " Your seller application has been rejected. Please check your email for further details or contact support.",

    // -----------------------product vallidations-------------------------------//

    storeLogoError: "Bussiness Logo required",
    productImgError: "Product Images is required",
    allreadyHaveSeller: "Already a seller",
    NO_TOKEN_PROVIDED: 'Unauthorized: No token provided',
    dataAddedSuccessfull: "Data Added Sucessfully",
    errorToSendingEmail: "Error sending email",
    pageNotFound: "404 Error, Page Not Found",
    dbConnectionError: 'Error when connecting to db:',
    dbConnectionSuccess: 'Connected to MySQL Server!',
    dbConnectionClosing: 'Closing database connection',
    dbError: 'Database connection error:',
    protocolConnectionLost: 'Database connection was lost. Reconnecting...',
    INVALID_OR_MISSING_TOKEN: 'Unauthorized: Invalid or missing token',
    INVALID_TOKEN: 'Unauthorized: Invalid token',
    USER_NOT_FOUND: 'User Not Found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    SELLER_CREATE: "Seller created successfully",
    SELLER_CREATE_Error: "Unable to create seller, please try again!",
    SELLER_NOT_AVAILABLE: "Seller Not Found",
    SELLER_UPDATE: "Seller updated successfully",
    SELLER_UPDATE_Error: "Unable to update seller, please try again!",
    ADD_PRODUCT_Error: "Unable to add product, please try again!",
    ADD_PRODUCT: "Product added successfully",
    UPDATE_PRODUCT: "Product updated successfully",
    UPDATE_PRODUCT_Error: "Unable to update product, please try again!",
    PRODUCT_NOT_AVAILABLE: "Product Not Found",
    PRODUCT_DELETE: "Product deleted successfully",
    PRODUCT_DELETE_ERROR: "Unable to deleted product, please try again!",
    ACCOUNT_SUSPENDED: "Your user account has been suspended. Please contact support for further assistance.",
    SELLER_ACCOUNT_SUSPENDED: "Your seller account has been suspended. Please contact support for further assistance.",


    //--------------------------------------- Admin Messages-------------------------------
    ADMIN_NOT_FOUND: 'Admin Not Found',
    INVALID_EMAIL_PASSWORD: 'Invalid email or password',
    LOGIN_SUCCESSFUL: 'Login Successful',
    VERIFY_EMAIL_FIRST: 'Please Verify your email first',
    INVALID_EXPIRED_TOKEN: 'Invalid or expired token',
    PASSWORD_CAN_NOT_SAME: 'Password cannot be the same as the previous password.',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully.',
    PASSWORD_RESET_FAILED: 'Failed to reset password.',
    ADMIN_PROFILE_FETCHED: 'Admin profile fetched successfully',
    CUREENT_NEW_REQUIERED: 'Current password and new password are required, and new password must be at least 8 characters long.',
    CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect.',
    PASSWORD_CAN_NOT_BE_SAME: 'Password cannot be the same as the previous password.',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
    USER_NOT_FOUNT: 'Users Not Found',
    SELLER_NOT_FOUNT: 'Sellers Not Found',
    USER_RETRIVED: 'Users Retrived Successfully!',
    SELLER_RETRIEVED: 'Sellers Retrived Successfully!',
    SUPPORT_NOT_FOUND: 'Supports Not Found',
    GROUP_DATA_NOT_FOUNT: 'Group Data Not Found',
    SUPPORT_RETRIVED: 'Supports Retrived Successfully',
    GROUP_DATA_RETRIVED: 'Group Data Retrived Successfully',
    DASHBOARD_DATA_RETRIVED: 'Dashboard data retrieved successfully',
    PRODUCT_RETRIVED: 'Products Retrived Successfully!',
    POST_RETRIVED: 'Posts Retrived Successfully!',
    POST_NOT_FOUND: 'Post Not Found',
    POST_DELETED: 'Post Deleted Successfully!',
    PASSWORD_RESET_LINK_SENT: (email) => `Password reset link sent to your email (${email}).`,
    USER_SUSPEND_UNSUSPENDED: (response_message) => `User ${response_message} Successfully`,
    ACTIVE_INACTIVE_SELLER: (response_message) => `Seller ${response_message} Successfully`,
    SELLER_APPOROVE_REJECT: (response_message) => `Seller ${response_message} Successfully`,


    SELLER_FOUND: "Seller found",
    ADMIN_BLOCK_USER: "You have been blocked by admin.",
    ADD_PRODUCT_To_Cart: "Product added to cart successfully",
    Cart_Added_Error: "Unable to add product in cart, please try again!",
    Product_Already_In_Cart: "Product already in cart!",
    USER_Cart_Error: "User can not buy own product.",
    OUT_OF_STOCK: "Product out of stock.",
    CART_UPDATED: "Cart updated successfully.",
    CART_UPDATED_ERROR: "Product is out of stock. You cannot add more of this product!",
    NO_PRODUCT_IN_CART: "No product found in cart!",
    CART_DELETE: "Cart product deleted successfully.",
    CART_DELETE_ERROR: "Unable to delere cart product, please try again!",
    CHANGE_PASSWORD_ERROR: "New password and old password must be different!",
    OLD_PASSWORD_ERROR: "Old password is incorrect!",
    UPDATE_PASSWORD: "Password change successfully.",
    UPDATE_PASSWORD_ERROR: "Unable to change password, please try again!",
    PRODUCT_CATEGORY_ERROR: "Product category already exist",
    ADD_PRODUCT_CATEGORY: "Product category added successfully.",
    ADD_PRODUCT_CATEGORY_ERROR: "Unable to add product category, please try again!",
    UPDATE_PRODUCT_CATEGORY: "Product category updated successfully.",
    UPDATE_PRODUCT_CATEGORY_ERROR: "Unable to update product category, please try again!",
    DELETE_PRODUCT_CATEGORY: "Product category deleted successfully.",
    DELETE_PRODUCT_CATEGORY_ERROR: "Unable to delete product category, please try again!",
    PRODUCT_CATEGORY_NOT_EXIST: "Product category not found!",
    PROMOTION_ADDED: "Promotion added successfully",
    PROMOTION_ADD_ERROR: "Unable to add promotion, please try again!",
    PROMOTION_Id_ERROR: "Promotion id is required",
    PROMOTION_UPDATED: "Promotion updated successfully",
    PROMOTION_UPDATE_ERROR: "Unable to update promotion, please try again!",
    PROMOTION_DELETE: "Promotion deleted successfully",
    PROMOTION_DELETE_ERROR: "Unable to delete promotion, please try again!",
    PROMOTION_NOT_FOUND: "Promotion not found!",
    INFLUENCER_IMAGE_ERROR: "Influencer image is required!",
    INFLUENCER_ADDED: "Influencer added successfully",
    INFLUENCER_ADD_ERROR: "Unable to add influencer, please try again!",
    INFLUENCER_UPDATED: "Influencer updated successfully",
    INFLUENCER_UPDATE_ERROR: "Unable to update influencer, please try again!",
    INFLUENCER_Id_ERROR: "Influencer id is required",
    INFLUENCER_DELETE: "Influencer deleted successfully",
    INFLUENCER_DELETE_ERROR: "Unable to delete influencer, please try again!",
    ADD_CATEGORY: "Category added successfully.",
    ADD_CATEGORY_ERROR: "Unable to add category, please try again!",
    UPDATE_CATEGORY: "Category updated successfully.",
    UPDATE_CATEGORY_ERROR: "Unable to update category, please try again!",
    DELETE_CATEGORY: "Category deleted successfully.",
    DELETE_CATEGORY_ERROR: "Unable to delete category, please try again!",
    ALREADY_AVAILABLE: "Already have this category!",
    ADD_FAVORIETS: "Product added to favorites successfully.",
    ADD_FAVORIETS_ERROR: "Unable to add product to favorites, please try again!",
    ALREADY_FAVORIETS: "Product already in favorites product list.",
    CHECKOUT_COMPLETED_SUCCESSFULLY: "Checkout completed successfully!",
    CHECKOUT_FAILED: "Unable to complete checkout, please try again!",
    REMOVE_FAVORITES: "You've successfully removed the product from your favorites!",
    REMOVE_FAVORITES_ERROR: "Oops! Couldn't remove the product. Please try again.",
    ADD_DELIVERY_ADDRESS: "address added successfully.",
    ADD_DELIVERY_ADDRESS_ERROR: "Unable to add address, please try again!",
    DATA_UPDATED: "Detail updated successfully",
    DATA_UPDATED_TO_FAILED: "Detail failed to update",
    APPLY_TO_SELLER_NOTIFICATION: "has applied to a seller",
    CHAT_CREATED_SUCCESSFULLY: "Chat created successfully",
    groupUpdatedSuccessfully: "Group updated successfully!",
    ORDER_SUMMARY_ADDED_SUCCESSFULLY: "Order summary added successfully",
    ORDER_SUMMARY_ADDED_FAILED: "Order summary added to failed",
    SHIPPING_ADDRESS_ADDED: "Shipping address added successfully.",
    FAILED_TO_ADD_SHIPPING_ADDRESS: "Failed to add shipping address.",
    SHIPPING_ADDRESS_UPDATE_SUCCESSFULLY: "Shipping address updated successfully!",
    FAILED_TO_UPDATE_SHIPPING_ADDRESS: "Failed to update the shipping address. Please try again later.",
    GRAPH_DATA_ERROR: "Graph Data Must be [yearly , monthly]",
    STORY_ADDED_SUCCESSFULLY: "Your story has been posted.",
    DELIVERY_STATUS_UPDATE_SUCCESSFULLY: "Delivery status updated successfully!",
    FAILED_TO_UPDATE_DELIVERY_STATUS: "Failed to update the delivery status. Please try again later.",
    SELLER_PAYOUT_SUCCESSFULLY: "Delivery status updated successfully!",
    SELLER_PAYOUT_FAILED: "Failed to pay seller. Please try again later.",

    // Admin commission
    ADMIN_COMMISSION_UPDATED_SUCCESSFULLY: "Admin commission updated successfully!",
    ADMIN_COMMISSION_UPDATED_ERROR: "Unable to update admin commission. Please try again later.",

    // --------------------seller-boost-product--------------------------------
    PROMOTION_PACKAGE_NOT_FOUND: "Promotion package not found!",
    PROMOTION_PACKAGE_FOUND_SUCCESSFULLY: "Promotion package found successfully!",
    PROMOTION_PACKAGE_ADDED_SUCCESSFULLY: "Promotion package added successfully!",
    PROMOTION_PACKAGE_ADDED_ERROR: "Unable to add promotion package. Please try again later.",
    PROMOTION_PACKAGE_UPDATED_SUCCESSFULLY: "Promotion package updated successfully!",

    linkToPay: "Link to pay for promotion",
    FETCH_BOOSTED_PRODUCTS: "Boosted Product Fetch Successfully",
    FAILED_FETCH_BOOSTED_PRODUCTS: "Failed to fetch Boosted Product",
    Boost_PRODUCT_RETRIVED: 'Boost Products Retrived Successfully!',
    Boosted_Product_Retrived: "Boost Post Retrived Successfully!",
    Boost_Promotional_post_Package_Update: "Boost Promotional Post Package Updated Successfully!",
    Boost_Promotional_post_Package_Update_Error: "Boost Promotional Post Package Updated Error!",
    Boost_Promotional_product_Package_Update: "Boost Promotional Product Package Updated Successfully!",
    Boost_Promotional_product_Package_Update_Error: "Boost Promotional Product Package Updated Error!",
    idPriceDurationIsRequire: "id || price || duration_days Is Required",
    PostBoostSuccessfully: "Post Boosted Successfully",
    PostBoostFailed: "Post Boost Failed",
    ProductBoostSuccessfully: "Product Boosted Successfully",
    ProductBoostFailed: "Product Boost Failed",
    SweepStakesPurchaseSuccess: "Sweepstake purchase successful!",
    SweepStakesPurchaseFailed: "Sweepstake purchase failed. Please try again later.",
    ORDER_PLACED_SUCCESSFULLY: "Order placed successfully!",
    ORDER_PLACED_FAILED: "Failed to place order. Please try again later.",
    postSharedSuccessfully: "Post shared successfully",
    postSharedFailed: "Failed to share post. Please try again later.",
    rechargeSuccessfully: "Recharge successfully",
    rechargeFailed: "Failed to recharge. Please try again later.",

    APPLY_TO_BECOME_INVESTOR_SUCCESSFULLY: "Your investor application has been submitted successfully.",
    APPLY_TO_BECOME_INVESTOR_FAILED: "Unable to submit your investor application. Please try again later.",
    APPLY_TO_BECOME_INVESTOR_MEDIA_ADDED_SUCCESSFULLY: "Supporting documents for your investor application have been uploaded successfully.",
    APPLY_TO_BECOME_INVESTOR_MEDIA_ADDED_FAILED: "Failed to add apply to become a investor media. Please try again later.",
    APPLY_TO_BECOME_INVESTOR_RETRIVED: "Investor application details retrieved successfully.",
    APPLY_TO_BECOME_INVESTOR_RETRIVED_FAILED: "Unable to retrieve investor application details. Please try again later.",
    RANCH_CREATED: "Ranch has been created successfully.",
    RANCH_CREATED_FAILED: "Unable to create ranch. Please try again later.",
    RANCH_MEDIA_ADDED_SUCCESSFULLY: "Ranch media added successfully",
    RANCH_MEDIA_ADDED_FAILED: "Failed to add ranch media. Please try again later.",
    RANCH_MEDIA_RETRIVED: "Ranch media retrieved successfully",
    RANCH_MEDIA_RETRIVED_FAILED: "Failed to retrieve ranch media. Please try again later.",
    RANCH_UPDATED: "Ranch updated successfully",
    INVESTER_APPLICATION_UPDATED: "Your investor application has been successfully found.",
    RANCH_OWNERSHIP_DASHBOARD: "Ranch dashboard data found successfully",

    // ------------------------- Investor Application Update -------------------------------------//
    INVESTOR_APPLICATION_UPDATED: "Your investor application has been updated successfully.",
    INVESTOR_APPLICATION_UPDATE_FAILED: "Unable to update your investor application. Please try again later.",

    RANCH_FETCHED_SUCCESSFULLY: "Ranches fetched successfully",    INVESTOR_APPLICATION_IS_PENDING: "Your investor application is currently pending. Please wait for approval.",
    INVESTOR_APPLICATION_REJECTED: "We regret to inform you that your investor application has been rejected.",
    INVESTOR_APPLICATION_NOT_FOUND: "Investor application not found. Please check your details.",
    INVESTOR_DASHBOARD_DATA_FETCHED: "Investor dashboard data fetched successfully",
};

export default messages;
